package com.bezkoder.springjwt.models;

public enum TypeContrat {
    SERVICE_CONTRACT,
    PRODUCT_PURCHASE_CONTRACT,
    SUBSCRIPTION_CONTRACT,
    LEASE_CONTRACT,
    PARTNERSHIP_AGREEMENT,
    LICENSE_AGREEMENT,
    EVENT_SERVICE_CONTRACT,
    MAINTENANCE_CONTRACT,
    RESEARCH_DEVELOPMENT_CONTRACT,
    EXCLUSIVE_DISTRIBUTION_AGREEMENT
}
